server:
  port: 8888
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/music_player?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

# mapper 映射文件位置
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true